
CREATE TABLE "User" (
  "id" VARCHAR(255) PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE "Task" (
  "id" VARCHAR(255) PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL,
  "status" VARCHAR(50) DEFAULT 'TODO',
  "priority" VARCHAR(50) DEFAULT 'MEDIUM',
  "dueDate" TIMESTAMP,
  "assignedToId" VARCHAR(255),
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL
);


CREATE INDEX ON "User" ("email");
CREATE INDEX ON "Task" ("status");
